const cols = [
  { title: 'invoiceNo', field: 'invoiceNo' },
  { title: 'invoicePrefix', field: 'invoicePrefix' },
  { title: 'storeId', field: 'storeId' },
  { title: 'storeName', field: 'storeName' },
  { title: 'storeUrl', field: 'storeUrl' },
  { title: 'customerId', field: 'customerId' },
  { title: 'customerGroupId', field: 'customerGroupId' },
  { title: 'firstname', field: 'firstname' },
  { title: 'lastname', field: 'lastname' },
  { title: 'email', field: 'email' },
  { title: 'telephone', field: 'telephone' },
  { title: 'fax', field: 'fax' },
  { title: 'customField', field: 'customField' },
  { title: 'paymentFirstname', field: 'paymentFirstname' },
  { title: 'paymentLastname', field: 'paymentLastname' },
  { title: 'paymentCompany', field: 'paymentCompany' },
  { title: 'paymentAddress1', field: 'paymentAddress1' },
  { title: 'paymentAddress2', field: 'paymentAddress2' },
  { title: 'paymentCity', field: 'paymentCity' },
  { title: 'paymentPostcode', field: 'paymentPostcode' },
  { title: 'paymentCountry', field: 'paymentCountry' },
  { title: 'paymentCountryId', field: 'paymentCountryId' },
  { title: 'paymentZone', field: 'paymentZone' },
  { title: 'paymentZoneId', field: 'paymentZoneId' },
  { title: 'paymentAddressFormat', field: 'paymentAddressFormat' },
  { title: 'paymentCustomField', field: 'paymentCustomField' },
  { title: 'paymentMethod', field: 'paymentMethod' },
  { title: 'paymentCode', field: 'paymentCode' },
  { title: 'shippingFirstname', field: 'shippingFirstname' },
  { title: 'shippingLastname', field: 'shippingLastname' },
  { title: 'shippingCompany', field: 'shippingCompany' },
  { title: 'shippingAddress1', field: 'shippingAddress1' },
  { title: 'shippingAddress2', field: 'shippingAddress2' },
  { title: 'shippingCity', field: 'shippingCity' },
  { title: 'shippingPostcode', field: 'shippingPostcode' },
  { title: 'shippingCountry', field: 'shippingCountry' },
  { title: 'shippingCountryId', field: 'shippingCountryId' },
  { title: 'shippingZone', field: 'shippingZone' },
  { title: 'shippingZoneId', field: 'shippingZoneId' },
  { title: 'shippingAddressFormat', field: 'shippingAddressFormat' },
  { title: 'shippingCustomField', field: 'shippingCustomField' },
  { title: 'shippingMethod', field: 'shippingMethod' },
  { title: 'shippingCode', field: 'shippingCode' },
  { title: 'comment', field: 'comment' },
  { title: 'total', field: 'total' },
  { title: 'orderStatusId', field: 'orderStatusId' },
  { title: 'affiliateId', field: 'affiliateId' },
  { title: 'commission', field: 'commission' },
  { title: 'marketingId', field: 'marketingId' },
  { title: 'tracking', field: 'tracking' },
  { title: 'languageId', field: 'languageId' },
  { title: 'currencyId', field: 'currencyId' },
  { title: 'currencyCode', field: 'currencyCode' },
  { title: 'currencyValue', field: 'currencyValue' },
  { title: 'ip', field: 'ip' },
  { title: 'forwardedIp', field: 'forwardedIp' },
  { title: 'userAgent', field: 'userAgent' },
  { title: 'acceptLanguage', field: 'acceptLanguage' },
  { title: 'dateAdded', field: 'dateAdded' },
  { title: 'dateModified', field: 'dateModified' },

];


export const OcOrder = {
  cols: cols,
  title: 'Table OcOrder',
  url: 'http://localhost:8080/jee7app/rest/ocorder/selectAll'
}